### PR TITLE
Add Windows support for wavplay

### PR DESCRIPTION
**Pull request by qrqiuren**
Using winsound module in python to play sounds on Windows.

```
+		elif sys.platform == "win32":
+			import winsound
+			winsound.PlaySound(filename, winsound.SND_FILENAME)
```

### CODE REVIEW

**Comment by randombrein** [comment]
@qrqiuren nice one, but the commit is very dirty.

**Comment by xserra** [comment]
what do you mean? I cannot test it. Can you propose a better implementation?

**Comment by qrqiuren** [comment]
@xserra @randombrein This commit just added support for playing wav file on windows. So that windows users can play wav file in models_GUI.py without any other modifications.

But my text editor automatically removes trailing spaces in each lines so that it is somewhat confusing while see it in diff.

**Comment by gentlecat** [comment]
It's usually better to split up functionality changes and cleanup into different commits.

**Pull request merged**
